### ISSUE TITLE
Readme.md update request

### ISSUE THREAD

**Issue by kriakiku** [joshdev8/AutoPlexx#8]
Hey, thank you for this project)

When trying to launch services for the first time, i get an error:

```
 ~/plex # docker compose up
WARN[0000] The "TELEGRAF_CFG_PATH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GRAFANA_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PLEX_HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PLEX_ADVERTISE_IP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_INFLUXDB_INIT_PORT" variable is not set. Defaulting to a blank string. 
invalid spec: :/etc/telegraf/telegraf.conf:rw: empty section between colons
```

Could you please complete the documentation?
I also have a question — is it possible to use Transmission without a VPN?

**Comment by kriakiku** [comment]
As far as I understand — docker-compose uses incorrect env

**Comment by joshdev8** [comment]
Hello!

I will update the README it looks like I forgot to add all of the env variables. Is your `.env` file in the same directory as the docker-compose.yml file? docker-compose should automatically grab any .env file that is in the same directory as the docker-compose.yml file. You can also manually pass the path to the env file via `docker-compose --env-file ./path/to/your-env-file.env up`. 

Try setting all of those variables in your .env file if they are missing, and let me know what docker says when you rerun the command.

**Comment by kriakiku** [comment]
**These variables are not in the Readme:**
TELEGRAF_CFG_PATH
GRAFANA_PORT
DOCKER_INFLUXDB_INIT_PORT

**These variables are in the example .env and docker-compose have different names:**
`HOSTNAME` => `PLEX_HOSTNAME`
`PLEX_ADVERTISE_IP` => `ADVERTISE_IP`
`OPENVPN_PASSWORD` => `PASSWORD` ⚠️ (same variables)
`TRANSMISSION_RPC_PASSWORD` => `PASSWORD` ⚠️ (same variables)

**Comment by joshdev8** [comment]
Thank you for documenting all those! I will update now.
